version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - git submodule update --init --recursive
      - virtualenv env
      - source env/bin/activate
      - pip install -U pip
      - pip install -r requirements.txt
      - nosetests test/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - pybossa/**/*
    - appspec.yml
    - scripts/*
